# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios.montagnes.qc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios.montagnes.qc

  target 'ios.montagnes.qcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios.montagnes.qcUITests' do
    # Pods for testing
  end

end
